### ISSUE TITLE
question

### ISSUE THREAD

**Issue by geraldstanje** [gevago01/Agglomerative-Clustering-#1]
Hi, is it possible to compare the result of your c++ implementation with the python implementation (e.g. scipy or scikit-learn) by using the same input?

**Comment by gevago01** [comment]
Hello,

 I have verified a branch of this repository (with minor changes) with a python implementation (i think it was scipy). I am very confident that it gives correct results, but if you want it for a serious project I would advise to double check it. 

Cheers,
Giannis.

**Comment by gevago01** [comment]
I also have a [scipy implementation](https://github.com/gevago01/scipy_k_means/blob/master/agglomerative.py). Just print the linkage_matrix variable to check that the distances are correct.
