### ISSUE TITLE
values.h ??

### ISSUE THREAD

**Issue by Raminmoslemi** [gevago01/Agglomerative-Clustering-#2]
I have problem in compiling your code.
In the agglomerate.cpp there id header file "values.h", but there is no header file this name in the repository.
Also, I removed this header and complied the project bu the code stuck  at   line 14: agglomerate.calculateInitialDistances();
 
 I really appreciate if you help me to solve the problem.

**Comment by gevago01** [comment]
Hello Raminmoslemi,

values.h is a C library, see [here](http://tigcc.ticalc.org/doc/values.html). I had a look and I don't think I use it anywhere. I have removed the include statement and added some instructions for running on Linux (see the README file).

I hope this helps,
Giannis

**Comment by gevago01** [comment]
I now have ran the source code and I can confirm that it terminates fine

**Comment by Raminmoslemi** [comment]
Thank you.
honestly, I am new in C++.   :D

**Comment by Raminmoslemi** [comment]
Now I can run the program, however I believe that  it does not converge when i use your data set "0". 
There is while loop inside inside agglomerate:: agglomerate 
while (prior_queue.size()!=0)......
I think  the value of prior_queue.size() should decrease while it reaches zero, but when i check its values  increases over the time.
Could you be kind enough to explain me how can run your sample set ?
Bests
Ramin

**Comment by gevago01** [comment]
Hello Ramin,

It increases over time but then it decreases to zero. I checked and it runs fine for me.

Giannis
